### ISSUE TITLE
Bad reliability / often changes of ONLINE status

### ISSUE THREAD

**Issue by pfink** [pfink/openhab2-flicbutton#2]
Quote by @dfrommi from PR #1 

> One more thing I've observed:
> I see quite frequent changes of ONLINE / OFFLINE status in the logs. And whenever the button is OFFLINE, events are not processed. However, flicd receives the button presses and correctly forwards events.
> The button is set to OFFLINE due to TimedOut connection state. Do you experience the same? 
> My buttons are of course not next to the Raspberry Pi, but some meters away. And I think that's the reason for the time-out.
> I'm currently running a version that doesn't set the button to OFFLINE when the disconnection reason is TimedOut. And that is working really well.

**Comment by pfink** [comment]
I also expierenced a reliability issue, but I didn't had the time to have a deeper look. Probably, the issue is the same. But I'm not sure if ignoring the TimedOut disconnect is the right way dealing with it. If you just go away with the button or remove the battery, I assume OpenHab would still showing ONLINE, wouldn't it?

Maybe a cleaner approach would be to ensure that the status is ONLINE before triggering the event?

**Comment by dfrommi** [comment]
Good idea to open an issue for this topic.

If the button is really not reachable for one of the reasons you've mentioned,  then `TimedOut` will probably not be the only disconnection reason. Needs to be verified, but I think `ConnectionEstablishmentFailed` will also happen in this case.

My code currently looks like this:

``` java
void flicConnectionStatusChanged(ConnectionStatus connectionStatus, DisconnectReason disconnectReason) {
    if (connectionStatus == ConnectionStatus.Disconnected) {
        if (disconnectReason == DisconnectReason.TimedOut) {
            logger.info("Button timed out - ignoring");
        } else {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.OFFLINE.COMMUNICATION_ERROR,
                    "Disconnect Reason: " + Objects.toString(disconnectReason));
        }
    } else {
        updateStatus(ThingStatus.ONLINE, ThingStatusDetail.NONE, "Button reconnected.");
    }
}
```

**Comment by pfink** [comment]
Unfortunately, there is not a different disconnect reason e.g. if you remove the battery (just tested it). I just applied fix 7d7a738, could you try if that works for you as well?

**Comment by dfrommi** [comment]
That's definitely a good thing to do. I will try as soon as possible.

But it still doesn't stop the button from switching between `ONLINE` and `OFFLINE`.
I see in the logs that just a few seconds after a button went offline, it goes back online again. If we set the button to `OFFLINE` only if it has stayed there for 15 seconds, then the problem should be solved.
- _on disconnection:_ create a timer with 15 seconds delay that sets the button `OFFLINE`
- _on (re-)connection:_ cancel the timer

I would still keep your safety-net, because it improves reliability even further.

**Comment by pfink** [comment]
Good idea!

**Comment by pfink** [comment]
Implemented. I think it would be good to check this change during everyday usage and share our experience here. As soon as we feel that everything is fine, I'll proceed with closure of this issue.

Grace period is set to 1 minute now. Let's see if it's really needed to have more.

**Comment by dfrommi** [comment]
Just installed it. So far looking good. I let you know if I'm experiencing OFFLINE issues

**Comment by pfink** [comment]
Seems to work fine -> closing.
