### ISSUE TITLE
Relicensing to EPL 2.0 with GPL 3.0 secondary license

### ISSUE THREAD

**Issue by pfink** [pfink/openhab2-flicbutton#6]
I'd like to [relicense this project under EPL 2.0 with GPL 3.0 as a secondary license](https://www.eclipse.org/legal/epl-2.0/faq.php#h.60mjudroo8e5).

@dfrommi: [Your consent is required](https://www.eclipse.org/legal/epl-2.0/faq.php#h.cktcxkzh8ks4), do you agree?

**Comment by dfrommi** [comment]
I hereby confirm that I agree to the license change.
